# Modify from pingcap/tidb.
version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - durationcheck
    # - errcheck
    - gosec
    - ineffassign
    - intrange
    # - lll
    - makezero
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unused
  settings:
    gosec:
      excludes:
        - G101
        - G106
        - G112
        - G115
        - G404
      severity: low
      confidence: low
    revive:
      max-open-files: 2048
      confidence: 0.1
      severity: error
      enable-all-rules: true
      rules:
        - name: add-constant
          arguments:
            - allowFloats: 0.0,0.,1.0,1.,2.0,2.
              allowInts: 0,1,2,3,4,5,6,7,8,9,10
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        - name: argument-limit
          arguments:
            - 15
          severity: warning
          disabled: false
        - name: atomic
          severity: warning
          disabled: false
        - name: banned-characters
          arguments:
            - Ω
            - Σ
            - σ
            - "7"
          severity: warning
          disabled: false
        - name: bare-return
          severity: warning
          disabled: true
        - name: blank-imports
          severity: warning
          disabled: false
        - name: bool-literal-in-expr
          severity: warning
          disabled: false
        - name: call-to-gc
          severity: warning
          disabled: false
        - name: cognitive-complexity
          arguments:
            - 200
          severity: warning
          disabled: false
        - name: comment-spacings
          arguments:
            - mypragma
            - otherpragma
          severity: warning
          disabled: false
        - name: confusing-naming
          severity: warning
          disabled: false
        - name: confusing-results
          severity: warning
          disabled: true
        - name: constant-logical-expr
          severity: warning
          disabled: false
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T,*github.com/user/repo/testing.Harness'
          severity: warning
          disabled: false
        - name: context-keys-type
          severity: warning
          disabled: false
        - name: cyclomatic
          arguments:
            - 100
          severity: warning
          disabled: false
        - name: datarace
          severity: warning
          disabled: false
        - name: deep-exit
          severity: warning
          disabled: false
        - name: defer
          arguments:
            - - call-chain
              - loop
          severity: warning
          disabled: false
        - name: dot-imports
          severity: warning
          disabled: false
        - name: duplicated-imports
          severity: warning
          disabled: false
        - name: early-return
          severity: warning
          disabled: false
        - name: empty-block
          severity: warning
          disabled: false
        - name: empty-lines
          severity: warning
          disabled: true
        - name: error-naming
          severity: warning
          disabled: false
        - name: error-return
          severity: warning
          disabled: false
        - name: error-strings
          severity: warning
          disabled: false
        - name: errorf
          severity: warning
          disabled: false
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
          severity: warning
          disabled: false
        - name: file-header
          arguments:
            - This is the text that must appear at the top of source files.
          severity: warning
          disabled: true
        - name: flag-parameter
          severity: warning
          disabled: false
        - name: function-result-limit
          arguments:
            - 6
          severity: warning
          disabled: false
        - name: function-length
          arguments:
            - 200
            - 0
          severity: warning
          disabled: false
        - name: get-return
          severity: warning
          disabled: false
        - name: identical-branches
          severity: warning
          disabled: false
        - name: if-return
          severity: warning
          disabled: false
        - name: increment-decrement
          severity: warning
          disabled: false
        - name: indent-error-flow
          severity: warning
          disabled: false
        - name: imports-blocklist
          arguments:
            - crypto/md5
            - crypto/sha1
          severity: warning
          disabled: false
        - name: import-shadowing
          severity: warning
          disabled: true
        - name: line-length-limit
          arguments:
            - 800
          severity: warning
          disabled: false
        - name: max-public-structs
          arguments:
            - 5
          severity: warning
          disabled: false
        - name: max-control-nesting
          arguments:
            - 10
          severity: warning
          disabled: false
        - name: modifies-parameter
          severity: warning
          disabled: true
        - name: modifies-value-receiver
          severity: warning
          disabled: false
        - name: nested-structs
          severity: warning
          disabled: false
        - name: optimize-operands-order
          severity: warning
          disabled: false
        - name: package-comments
          severity: warning
          disabled: false
        - name: range
          severity: warning
          disabled: false
        - name: range-val-in-closure
          severity: warning
          disabled: false
        - name: range-val-address
          severity: warning
          disabled: false
        - name: receiver-naming
          severity: warning
          disabled: false
        - name: redefines-builtin-id
          severity: warning
          disabled: false
        - name: string-of-int
          severity: warning
          disabled: false
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: false
        - name: struct-tag
          arguments:
            - json,inline
            - bson,outline,gnu
          severity: warning
          disabled: false
        - name: superfluous-else
          severity: warning
          disabled: false
        - name: time-equal
          severity: warning
          disabled: false
        - name: time-naming
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
          severity: warning
          disabled: true
        - name: var-declaration
          severity: warning
          disabled: false
        - name: unconditional-recursion
          severity: warning
          disabled: false
        - name: unexported-naming
          severity: warning
          disabled: false
        - name: unexported-return
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
            - fmt.Fprint
            - fmt.Fprintln
            - myFunction
            - strings.Builder.WriteByte
            - strings.Builder.WriteString
            - bufio.Writer.Write
            - bufio.Writer.WriteRune
            - bufio.Writer.WriteByte
            - bufio.Writer.WriteString
            - bytes.Buffer.WriteByte
            - bytes.Buffer.Write
          severity: warning
          disabled: false
        - name: unnecessary-stmt
          severity: warning
          disabled: false
        - name: unreachable-code
          severity: warning
          disabled: false
        - name: unused-parameter
          severity: warning
          disabled: false
        - name: unused-receiver
          severity: warning
          disabled: false
        - name: useless-break
          severity: warning
          disabled: false
        - name: waitgroup-by-value
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - -SA2002
        - -ST1003
        - S1002
        - S1004
        - S1007
        - S1009
        - S1010
        - S1012
        - S1019
        - S1020
        - S1021
        - S1024
        - S1030
        - SA2*
        - SA3*
        - SA4009
        - SA5*
        - SA6000
        - SA6001
        - SA6005
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - makezero
          - rowserrcheck
          - revive
        path: _test\.go
    paths:
      - parser$
      - example$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
  exclusions:
    generated: lax
    paths:
      - parser$
      - example$
